
# generated by: jx gitops variables
export APP_NAME="nodey553"
export BRANCH_NAME="master"
export BUILD_NUMBER="3"
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jstrachan"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export MINK_AS="tekton-bot"
export MINK_IMAGE="gcr.io/jstrachan/nodey553:1.0.3"
export PIPELINE_KIND="release"
export REPO_NAME="nodey553"
export REPO_OWNER="jstrachan"
export VERSION="1.0.3"


# content from git...

# generated by: jx gitops variables
export APP_NAME="nodey553"
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jenkins-x-labs-bdd"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080"
export MINK_AS="tekton-bot"
export MINK_IMAGE="gcr.io/jenkins-x-labs-bdd/nodey553:2.0.1300-dev"
export PIPELINE_KIND="release"
export REPO_NAME="nodey553"
export REPO_OWNER="jstrachan"
export VERSION="2.0.1300-dev"


